package live.airuncoach.airuncoach.domain.model

data class User(
    val id: String,
    val email: String,
    val name: String,
    val location: String? = null,
    val age: Int? = null,
    val dob: String? = null,
    val gender: String? = null,
    val height: Double? = null,
    val weight: Double? = null,
    val fitnessLevel: String? = null,
    val desiredFitnessLevel: String? = null,
    val coachName: String = "AI Coach",
    val coachGender: String = "male",
    val coachAccent: String = "british",
    val coachTone: String = "energetic",
    val profilePic: String? = null,
    val distanceMinKm: Float = 0f,
    val distanceMaxKm: Float = 50f,
    val distanceDecimalsEnabled: Boolean = false,
    val subscriptionTier: String? = null,
    val subscriptionStatus: String? = null,
    val distanceScale: String? = null,
    // In-Run AI Coaching feature preferences (synced with server)
    val coachPaceEnabled: Boolean = true,
    val coachNavigationEnabled: Boolean = true,
    val coachElevationEnabled: Boolean = true,
    val coachHeartRateEnabled: Boolean = true,
    val coachCadenceStrideEnabled: Boolean = true,
    val coachKmSplitsEnabled: Boolean = true,
    val coachStruggleEnabled: Boolean = true,
    val coachMotivationalEnabled: Boolean = true,
    val coachHalfKmCheckInEnabled: Boolean = true,
    val coachKmSplitIntervalKm: Int = 1
)
