/**
 * SessionCoaching Models
 *
 * Server-side models for session coaching data.
 * Mirrors SessionCoaching.kt on Android for consistency.
 *
 * Key principle: Works for ANY session type (current or future).
 * No hardcoded branches — all coaching is dynamically generated by AI.
 */

import { Timestamp } from 'firebase-admin/firestore';

/**
 * SessionCoaching
 * Complete coaching plan for a single training session
 */
export interface SessionCoaching {
  id: string;
  sessionId: string;
  workoutId: string;
  sessionType: string;  // "easy", "interval", "tempo", "long_run", "recovery", etc.
  sessionGoal: string;  // "speed", "endurance", "recovery", "threshold", "power"

  phases: CoachingPhase[];
  triggers: CoachingTrigger[];
  targetMetrics: TargetMetrics;

  coachingTone: string;  // "encouraging", "technical", "calm", "motivational"
  cueingStrategy: string;  // "interval", "threshold", "paced", "freerun"

  preRunBrief: string;  // Pre-run coaching summary
  whyThisSession: string;  // Explanation of session purpose
  sessionInstructions?: string;

  createdAt: Timestamp;
  generatedBy: string;  // "AI" or "user_custom"
}

/**
 * CoachingPhase
 * A distinct phase of the session (warmup, rep, cooldown, etc.)
 */
export interface CoachingPhase {
  name: string;  // "warmup", "interval_rep_1", "recovery_jog", "main_effort", "cooldown"
  order: number;  // Phase sequence (0-indexed)

  durationMinutes?: number;  // e.g., 10 for a 10-min warmup
  distanceKm?: number;  // e.g., 2.0 for a 2km interval

  targetPaceMin?: number;  // sec/km (e.g., 360 = 6:00/km)
  targetPaceMax?: number;  // sec/km
  targetHRMin?: number;  // BPM
  targetHRMax?: number;  // BPM

  effort: string;  // "easy", "steady", "moderate", "hard", "threshold", "race", "recovery"
  coachingFocus: string;  // "relaxation", "rhythm", "power", "pace_control", "endurance"

  phaseInstructions?: string;
}

/**
 * CoachingTrigger
 * A condition that fires during the run to send a coaching cue
 */
export interface CoachingTrigger {
  id: string;
  type: string;  // "phase_start", "phase_end", "pace_deviation", "hr_zone", "milestone", "custom"

  // Condition description
  // e.g., "pace > target + 30 sec", "hr < 120", "time = 5:00"
  condition: string;

  // AI-generated coaching message
  message: string;

  // Fire frequency
  // "once" = fire once per phase
  // "repeating_3min" = every 3 minutes
  // "on_condition" = when condition changes
  frequency: string;

  // Alternative messages for variety
  alternativeMessages?: string[];

  // Should this trigger an alert?
  // "vibrate", "tone", "none"
  alertType?: string;

  // Suppress if runner is in these intensity zones
  suppressWhenIntensity?: string[];  // ["z1", "z2"]
}

/**
 * TargetMetrics
 * Overall session targets and characteristics
 */
export interface TargetMetrics {
  sessionType: string;  // e.g., "intervals", "long_run", "recovery"
  totalDurationMinutes: number;
  totalDistanceKm: number;

  // What's the primary focus?
  primaryMetric: string;  // "pace", "heart_rate", "effort", "distance", "time"
  secondaryMetric?: string;  // "pace", "heart_rate", "cadence"

  // Expected pace range for main effort
  mainEffortPaceMin?: number;  // sec/km
  mainEffortPaceMax?: number;  // sec/km

  // Expected HR zone
  mainEffortHRMin?: number;  // BPM
  mainEffortHRMax?: number;  // BPM

  // Session structure
  structure: string;  // "continuous", "repeats", "progression", "threshold_block"

  // Characteristics
  isSpeedWork: boolean;
  isEnduranceWork: boolean;
  isStrengthWork: boolean;
  isRecovery: boolean;
}

/**
 * LiveCoachingState
 * Tracks coaching state during a run
 */
export interface LiveCoachingState {
  sessionCoachingId: string;
  currentPhaseIndex: number;
  firedTriggerIds: Set<string>;
  lastCoachingCueAt?: Timestamp;
  totalCuesGiven: number;
}

/**
 * Request to generate session coaching
 * Called when preparing a session for a run
 */
export interface GenerateSessionCoachingRequest {
  sessionId: string;
  workoutId: string;
  sessionType: string;
  sessionGoal: string;
  targetDurationMinutes: number;
  targetDistanceKm: number;
  targetPaceMin?: number;
  targetPaceMax?: number;
  targetHRMin?: number;
  targetHRMax?: number;
  runnerProfile: {
    age: number;
    gender: string;
    fitnessLevel: string;
    recentPaceAvg?: number;
    recentHRAvg?: number;
    injuries?: string[];
  };
  sessionInstructions?: string;
  recentRuns?: any[];  // Last 10 runs for context
}

/**
 * Response with generated session coaching
 */
export interface GenerateSessionCoachingResponse {
  sessionCoaching: SessionCoaching;
  generationTime: number;  // ms
  model: string;  // "gpt-4o"
}
