@file:OptIn(ExperimentalFoundationApi::class)

package live.airuncoach.airuncoach.ui.screens

import androidx.compose.foundation.ExperimentalFoundationApi
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.pager.HorizontalPager
import androidx.compose.foundation.pager.PagerState
import androidx.compose.foundation.pager.rememberPagerState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.DirectionsRun
import androidx.compose.material.icons.filled.CloudUpload
import androidx.compose.material.icons.filled.CloudDownload
import androidx.compose.material.icons.filled.EmojiEvents
import androidx.compose.material.icons.filled.Flag
import androidx.compose.material.icons.filled.Groups
import androidx.compose.material.icons.filled.Map
import androidx.compose.material.icons.filled.Psychology
import androidx.compose.material.icons.filled.SensorOccupied
import androidx.compose.material.icons.filled.ShareLocation
import androidx.compose.material.icons.filled.Watch
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlinx.coroutines.launch
import live.airuncoach.airuncoach.ui.theme.BorderRadius
import live.airuncoach.airuncoach.ui.theme.Colors
import live.airuncoach.airuncoach.ui.theme.Spacing
import live.airuncoach.airuncoach.util.AppAnalytics
import kotlin.math.absoluteValue

/**
 * Illustrated feature-tour carousel, offered as an option from [OnboardingSubscriptionScreen]
 * so new users can see what the app actually does before landing cold on the dashboard.
 *
 * Deliberately a static, no-navigation-risk carousel rather than a live walkthrough of the
 * real screens — one card per feature with an icon + short explanation. See MainScreen.kt's
 * "onboarding_tour" route for how this is reached via MainActivity.pendingDeepLink.
 */
private data class TourPage(
    val icon: ImageVector,
    val title: String,
    val description: String,
)

private val TOUR_PAGES = listOf(
    TourPage(
        icon = Icons.Filled.Flag,
        title = "Set Your Goals",
        description = "Tell us what you're working towards — a race, a distance PB, or just building a consistent habit — and Ai Run Coach tailors everything else around it.",
    ),
    TourPage(
        icon = Icons.Filled.Psychology,
        title = "AI Training Plans",
        description = "Get a personalised training plan generated by AI, built around your goal, fitness level, and schedule — and adjusted automatically as your training progresses.",
    ),
    TourPage(
        icon = Icons.Filled.EmojiEvents,
        title = "Run Summary & Insights",
        description = "Every run gets a full breakdown — pace, splits, heart rate, elevation, and an AI-written summary of how it went and what to focus on next.",
    ),
    TourPage(
        icon = Icons.Filled.CloudUpload,
        title = "Push Runs to Strava",
        description = "Finish a run with Ai Run Coach and send it straight to Strava with one tap — no manual re-entry.",
    ),
    TourPage(
        icon = Icons.Filled.CloudDownload,
        title = "Import Runs from Strava",
        description = "Already have run history on Strava? Bring it into Ai Run Coach so your stats, trends, and AI coaching all start from your real training history.",
    ),
    TourPage(
        icon = Icons.Filled.SensorOccupied,
        title = "Connected Devices",
        description = "Manage every device paired with Ai Run Coach in one place — see what's connected and add new ones any time from your profile.",
    ),
    TourPage(
        icon = Icons.Filled.Watch,
        title = "Connect Your Watch",
        description = "Pair an Apple Watch or Garmin watch to track heart rate, cadence, and GPS directly from your wrist, with live coaching cues sent straight to it.",
    ),
    TourPage(
        icon = Icons.Filled.Groups,
        title = "Group Runs",
        description = "Run together, even when you're apart — create or join a Group Run and see everyone's live progress in one shared session.",
    ),
    TourPage(
        icon = Icons.Filled.ShareLocation,
        title = "Live Tracking",
        description = "Start a live tracking session so friends or family can follow your run in real time — great for safety on solo runs.",
    ),
    TourPage(
        icon = Icons.AutoMirrored.Filled.DirectionsRun,
        title = "Run Without a Route",
        description = "Don't want to plan ahead? Just start running — Ai Run Coach tracks and coaches you live with no route required.",
    ),
    TourPage(
        icon = Icons.Filled.Map,
        title = "Create a Run Route",
        description = "Prefer to plan ahead? Generate a custom route for your target distance, or build your own, before you head out the door.",
    ),
)

@Composable
fun OnboardingTourScreen(
    onFinish: () -> Unit,
) {
    val context = LocalContext.current
    val pagerState = rememberPagerState(pageCount = { TOUR_PAGES.size })

    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(Colors.backgroundRoot)
    ) {
        // Top bar — Skip always available, never trap the user in the tour.
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = Spacing.lg, vertical = Spacing.md),
            horizontalArrangement = Arrangement.End,
            verticalAlignment = Alignment.CenterVertically,
        ) {
            TextButton(onClick = {
                AppAnalytics.logEvent(context, AppAnalytics.Event.ONBOARDING_TOUR_SKIPPED)
                onFinish()
            }) {
                Text(
                    text = "Skip",
                    fontSize = 14.sp,
                    fontWeight = FontWeight.SemiBold,
                    color = Colors.textSecondary,
                )
            }
        }

        HorizontalPager(
            state = pagerState,
            modifier = Modifier
                .weight(1f)
                .fillMaxWidth(),
        ) { page ->
            TourPageContent(TOUR_PAGES[page])
        }

        TourPageIndicator(
            pageCount = TOUR_PAGES.size,
            pagerState = pagerState,
            modifier = Modifier
                .fillMaxWidth()
                .padding(vertical = Spacing.lg),
        )

        val isLastPage = pagerState.currentPage == TOUR_PAGES.lastIndex
        val coroutineScope = rememberCoroutineScope()

        Button(
            onClick = {
                if (isLastPage) {
                    AppAnalytics.logEvent(context, AppAnalytics.Event.ONBOARDING_TOUR_COMPLETED)
                    onFinish()
                } else {
                    coroutineScope.launch {
                        pagerState.animateScrollToPage(pagerState.currentPage + 1)
                    }
                }
            },
            modifier = Modifier
                .fillMaxWidth()
                .height(56.dp)
                .padding(horizontal = Spacing.lg)
                .padding(bottom = Spacing.xl),
            colors = ButtonDefaults.buttonColors(
                containerColor = Colors.primary,
                contentColor = Colors.buttonText,
            ),
            shape = RoundedCornerShape(BorderRadius.lg),
        ) {
            Text(
                text = if (isLastPage) "Get Started" else "Next",
                fontWeight = FontWeight.Bold,
                fontSize = 16.sp,
            )
        }
    }
}

@Composable
private fun TourPageContent(page: TourPage) {
    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(horizontal = Spacing.xl),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center,
    ) {
        Box(
            modifier = Modifier
                .size(96.dp)
                .background(Colors.primary.copy(alpha = 0.12f), CircleShape),
            contentAlignment = Alignment.Center,
        ) {
            Icon(
                imageVector = page.icon,
                contentDescription = null,
                tint = Colors.primary,
                modifier = Modifier.size(44.dp),
            )
        }
        Spacer(modifier = Modifier.height(Spacing.xl))
        Text(
            text = page.title,
            fontSize = 22.sp,
            fontWeight = FontWeight.Bold,
            color = Colors.textPrimary,
            textAlign = TextAlign.Center,
        )
        Spacer(modifier = Modifier.height(Spacing.md))
        Text(
            text = page.description,
            fontSize = 15.sp,
            color = Colors.textSecondary,
            textAlign = TextAlign.Center,
            lineHeight = 22.sp,
        )
    }
}

@Composable
private fun TourPageIndicator(
    pageCount: Int,
    pagerState: PagerState,
    modifier: Modifier = Modifier,
) {
    Row(
        modifier = modifier,
        horizontalArrangement = Arrangement.Center,
    ) {
        repeat(pageCount) { index ->
            val distance = (pagerState.currentPage - index).absoluteValue
            val isCurrent = distance == 0
            Box(
                modifier = Modifier
                    .padding(horizontal = 3.dp)
                    .size(if (isCurrent) 9.dp else 7.dp)
                    .background(
                        color = if (isCurrent) Colors.primary else Colors.textMuted.copy(alpha = 0.4f),
                        shape = CircleShape,
                    ),
            )
        }
    }
}
