@file:OptIn(ExperimentalFoundationApi::class)

package live.airuncoach.airuncoach.ui.screens

import androidx.compose.foundation.ExperimentalFoundationApi
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.pager.HorizontalPager
import androidx.compose.foundation.pager.PagerState
import androidx.compose.foundation.pager.rememberPagerState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.DirectionsRun
import androidx.compose.material.icons.filled.CloudUpload
import androidx.compose.material.icons.filled.CloudDownload
import androidx.compose.material.icons.filled.EmojiEvents
import androidx.compose.material.icons.filled.Flag
import androidx.compose.material.icons.filled.Groups
import androidx.compose.material.icons.filled.HealthAndSafety
import androidx.compose.material.icons.filled.Map
import androidx.compose.material.icons.filled.PhoneAndroid
import androidx.compose.material.icons.filled.Psychology
import androidx.compose.material.icons.filled.SensorOccupied
import androidx.compose.material.icons.filled.ShareLocation
import androidx.compose.material.icons.filled.Watch
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlinx.coroutines.launch
import live.airuncoach.airuncoach.ui.theme.BorderRadius
import live.airuncoach.airuncoach.ui.theme.Colors
import live.airuncoach.airuncoach.ui.theme.Spacing
import live.airuncoach.airuncoach.util.AppAnalytics
import kotlin.math.absoluteValue

/**
 * Illustrated feature-tour carousel, offered as an option from [OnboardingSubscriptionScreen]
 * so new users can see what the app actually does before landing cold on the dashboard.
 *
 * Deliberately a static, no-navigation-risk carousel rather than a live walkthrough of the
 * real screens — one card per feature with an icon + short explanation. See MainScreen.kt's
 * "onboarding_tour" route for how this is reached via MainActivity.pendingDeepLink.
 *
 * Opens with a device-choice question (Apple Watch / Garmin Watch / Phone only) so the rest of
 * the tour can skip whichever watch-brand page doesn't apply, and so the two run-start pages
 * (Run Without a Route, Create a Run Route) can correctly describe "Prepare for Watch" only for
 * users who actually have a watch to prepare for.
 */
private enum class TourWatchChoice { APPLE_WATCH, GARMIN_WATCH, PHONE_ONLY }

private data class TourPage(
    val icon: ImageVector,
    val title: String,
    val description: String,
)

private fun buildTourPages(choice: TourWatchChoice): List<TourPage> {
    val hasWatch = choice != TourWatchChoice.PHONE_ONLY
    val pages = mutableListOf<TourPage>()

    pages += TourPage(
        icon = Icons.Filled.Flag,
        title = "Set Your Goals",
        description = "Tell us what you're working towards — a race, a distance PB, or just building a consistent habit — and Ai Run Coach tailors everything else around it.",
    )
    pages += TourPage(
        icon = Icons.Filled.Psychology,
        title = "AI Training Plans",
        description = "Get a personalised training plan generated by AI, built around your goal, fitness level, and schedule — and adjusted automatically as your training progresses.",
    )
    pages += TourPage(
        icon = Icons.Filled.HealthAndSafety,
        title = "Injuries & Conditions",
        description = "Dealing with an injury or an ongoing condition? Log it in your profile so your AI Training Plan trains around it — adjusting intensity, avoiding aggravating workouts, and adapting as you recover.",
    )
    pages += TourPage(
        icon = Icons.Filled.SensorOccupied,
        title = "Connected Devices",
        description = "Manage every device paired with Ai Run Coach from your profile — see what's connected, and add or remove devices any time.",
    )
    when (choice) {
        TourWatchChoice.APPLE_WATCH -> pages += TourPage(
            icon = Icons.Filled.Watch,
            title = "Connect Your Apple Watch",
            description = "Pair your Apple Watch from Connected Devices to track heart rate, cadence, and GPS directly from your wrist, with live coaching cues sent straight to it.",
        )
        TourWatchChoice.GARMIN_WATCH -> pages += TourPage(
            icon = Icons.Filled.Watch,
            title = "Connect Your Garmin Watch",
            description = "Pair your Garmin watch from Connected Devices to track heart rate, cadence, and GPS directly from your wrist, with live coaching cues sent straight to it.",
        )
        TourWatchChoice.PHONE_ONLY -> Unit // No watch pairing step to show.
    }
    pages += TourPage(
        icon = Icons.Filled.Groups,
        title = "Group Runs",
        description = "Run together, even when you're apart — create or join a Group Run and see everyone's live progress in one shared session.",
    )
    pages += TourPage(
        icon = Icons.Filled.ShareLocation,
        title = "Live Tracking",
        description = "Start a live tracking session so friends or family can follow your run in real time — great for safety on solo runs.",
    )
    pages += TourPage(
        icon = Icons.AutoMirrored.Filled.DirectionsRun,
        title = "Run Without a Route",
        description = if (hasWatch) {
            "Don't want to plan ahead? Just start running. Choose \"Prepare for Watch\" to start the session from your watch, or \"Start on Phone\" to begin right here — either way, Ai Run Coach tracks and coaches you live with no route required."
        } else {
            "Don't want to plan ahead? Just tap Start — Ai Run Coach tracks and coaches you live with no route required, right from your phone."
        },
    )
    pages += TourPage(
        icon = Icons.Filled.Map,
        title = "Create a Run Route",
        description = if (hasWatch) {
            "Prefer to plan ahead? Generate a custom route for your target distance, or build your own. When you're ready, choose \"Prepare for Watch\" to start from your wrist, or \"Start on Phone\" to begin right here."
        } else {
            "Prefer to plan ahead? Generate a custom route for your target distance, or build your own, before you head out the door."
        },
    )
    pages += TourPage(
        icon = Icons.Filled.EmojiEvents,
        title = "Run Summary & Insights",
        description = "Every run gets a full breakdown — pace, splits, heart rate, elevation, and an AI-written summary of how it went and what to focus on next.",
    )
    pages += TourPage(
        icon = Icons.Filled.CloudUpload,
        title = "Push Runs to Strava",
        description = "Finish a run with Ai Run Coach and send it straight to Strava with one tap — no manual re-entry.",
    )
    pages += TourPage(
        icon = Icons.Filled.CloudDownload,
        title = "Import Runs from Strava",
        description = "Already have run history on Strava? Bring it into Ai Run Coach so your stats, trends, and AI coaching all start from your real training history.",
    )
    return pages
}

@Composable
fun OnboardingTourScreen(
    onFinish: () -> Unit,
) {
    var watchChoice by remember { mutableStateOf<TourWatchChoice?>(null) }

    if (watchChoice == null) {
        WatchChoiceScreen(
            onChoose = { watchChoice = it },
            onSkip = onFinish,
        )
    } else {
        TourPagerScreen(
            pages = remember(watchChoice) { buildTourPages(watchChoice!!) },
            onFinish = onFinish,
        )
    }
}

@Composable
private fun WatchChoiceScreen(
    onChoose: (TourWatchChoice) -> Unit,
    onSkip: () -> Unit,
) {
    val context = LocalContext.current

    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(Colors.backgroundRoot),
    ) {
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = Spacing.lg, vertical = Spacing.md),
            horizontalArrangement = Arrangement.End,
        ) {
            TextButton(onClick = {
                AppAnalytics.logEvent(context, AppAnalytics.Event.ONBOARDING_TOUR_SKIPPED)
                onSkip()
            }) {
                Text(
                    text = "Skip",
                    fontSize = 14.sp,
                    fontWeight = FontWeight.SemiBold,
                    color = Colors.textSecondary,
                )
            }
        }

        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(horizontal = Spacing.xl),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.Center,
        ) {
            Text(
                text = "How will you run with Ai Run Coach?",
                fontSize = 22.sp,
                fontWeight = FontWeight.Bold,
                color = Colors.textPrimary,
                textAlign = TextAlign.Center,
            )
            Spacer(modifier = Modifier.height(Spacing.sm))
            Text(
                text = "We'll tailor the rest of this tour to what you're using.",
                fontSize = 14.sp,
                color = Colors.textSecondary,
                textAlign = TextAlign.Center,
            )
            Spacer(modifier = Modifier.height(Spacing.xl))

            WatchChoiceOption(
                icon = Icons.Filled.Watch,
                label = "Apple Watch",
                onClick = { onChoose(TourWatchChoice.APPLE_WATCH) },
            )
            Spacer(modifier = Modifier.height(Spacing.sm))
            WatchChoiceOption(
                icon = Icons.Filled.Watch,
                label = "Garmin Watch",
                onClick = { onChoose(TourWatchChoice.GARMIN_WATCH) },
            )
            Spacer(modifier = Modifier.height(Spacing.sm))
            WatchChoiceOption(
                icon = Icons.Filled.PhoneAndroid,
                label = "Phone only",
                onClick = { onChoose(TourWatchChoice.PHONE_ONLY) },
            )
        }
    }
}

@Composable
private fun WatchChoiceOption(
    icon: ImageVector,
    label: String,
    onClick: () -> Unit,
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .border(1.dp, Colors.primary.copy(alpha = 0.3f), RoundedCornerShape(BorderRadius.lg))
            .clickable(onClick = onClick)
            .padding(horizontal = Spacing.lg, vertical = Spacing.lg),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Icon(
            imageVector = icon,
            contentDescription = null,
            tint = Colors.primary,
            modifier = Modifier.size(24.dp),
        )
        Spacer(modifier = Modifier.width(Spacing.md))
        Text(
            text = label,
            fontSize = 16.sp,
            fontWeight = FontWeight.SemiBold,
            color = Colors.textPrimary,
        )
    }
}

@Composable
private fun TourPagerScreen(
    pages: List<TourPage>,
    onFinish: () -> Unit,
) {
    val context = LocalContext.current
    val pagerState = rememberPagerState(pageCount = { pages.size })

    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(Colors.backgroundRoot)
    ) {
        // Top bar — Skip always available, never trap the user in the tour.
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = Spacing.lg, vertical = Spacing.md),
            horizontalArrangement = Arrangement.End,
            verticalAlignment = Alignment.CenterVertically,
        ) {
            TextButton(onClick = {
                AppAnalytics.logEvent(context, AppAnalytics.Event.ONBOARDING_TOUR_SKIPPED)
                onFinish()
            }) {
                Text(
                    text = "Skip",
                    fontSize = 14.sp,
                    fontWeight = FontWeight.SemiBold,
                    color = Colors.textSecondary,
                )
            }
        }

        HorizontalPager(
            state = pagerState,
            modifier = Modifier
                .weight(1f)
                .fillMaxWidth(),
        ) { page ->
            TourPageContent(pages[page])
        }

        TourPageIndicator(
            pageCount = pages.size,
            pagerState = pagerState,
            modifier = Modifier
                .fillMaxWidth()
                .padding(vertical = Spacing.lg),
        )

        val isLastPage = pagerState.currentPage == pages.lastIndex
        val coroutineScope = rememberCoroutineScope()

        Button(
            onClick = {
                if (isLastPage) {
                    AppAnalytics.logEvent(context, AppAnalytics.Event.ONBOARDING_TOUR_COMPLETED)
                    onFinish()
                } else {
                    coroutineScope.launch {
                        pagerState.animateScrollToPage(pagerState.currentPage + 1)
                    }
                }
            },
            modifier = Modifier
                .fillMaxWidth()
                .height(56.dp)
                .padding(horizontal = Spacing.lg)
                .padding(bottom = Spacing.xl),
            colors = ButtonDefaults.buttonColors(
                containerColor = Colors.primary,
                contentColor = Colors.buttonText,
            ),
            shape = RoundedCornerShape(BorderRadius.lg),
        ) {
            Text(
                text = if (isLastPage) "Get Started" else "Next",
                fontWeight = FontWeight.Bold,
                fontSize = 16.sp,
            )
        }
    }
}

@Composable
private fun TourPageContent(page: TourPage) {
    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(horizontal = Spacing.xl),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center,
    ) {
        Box(
            modifier = Modifier
                .size(96.dp)
                .background(Colors.primary.copy(alpha = 0.12f), CircleShape),
            contentAlignment = Alignment.Center,
        ) {
            Icon(
                imageVector = page.icon,
                contentDescription = null,
                tint = Colors.primary,
                modifier = Modifier.size(44.dp),
            )
        }
        Spacer(modifier = Modifier.height(Spacing.xl))
        Text(
            text = page.title,
            fontSize = 22.sp,
            fontWeight = FontWeight.Bold,
            color = Colors.textPrimary,
            textAlign = TextAlign.Center,
        )
        Spacer(modifier = Modifier.height(Spacing.md))
        Text(
            text = page.description,
            fontSize = 15.sp,
            color = Colors.textSecondary,
            textAlign = TextAlign.Center,
            lineHeight = 22.sp,
        )
    }
}

@Composable
private fun TourPageIndicator(
    pageCount: Int,
    pagerState: PagerState,
    modifier: Modifier = Modifier,
) {
    Row(
        modifier = modifier,
        horizontalArrangement = Arrangement.Center,
    ) {
        repeat(pageCount) { index ->
            val distance = (pagerState.currentPage - index).absoluteValue
            val isCurrent = distance == 0
            Box(
                modifier = Modifier
                    .padding(horizontal = 3.dp)
                    .size(if (isCurrent) 9.dp else 7.dp)
                    .background(
                        color = if (isCurrent) Colors.primary else Colors.textMuted.copy(alpha = 0.4f),
                        shape = CircleShape,
                    ),
            )
        }
    }
}
